FROM python:3.11-slim-bookworm

RUN apt-get update -y && apt-get upgrade -y

WORKDIR /defaultpage

COPY requirements.txt .

RUN pip3 install -r requirements.txt
RUN pip3 install pip install django-cors-headers
RUN pip3 install djangorestframework
RUN pip3 install requests

CMD ["python", "main.py"]